#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.env"

cat > "${CONFIG_FILE}" <<EOF
# Auto-generated for the current 2xH800 / VSCode Remote SSH tree.
# Generated by make_config_for_current_tree.sh

PROJECT_ROOT="${PROJECT_ROOT}"
SOURCE_ROOT="\${PROJECT_ROOT}/sources"

HF_HOME="\${PROJECT_ROOT}/.cache/huggingface"
HF_TOKEN=""
MODELSCOPE_CACHE="\${PROJECT_ROOT}/.cache/modelscope"

CUDA_VISIBLE_DEVICES="0,1"
DREAMZERO_CUDA_VISIBLE_DEVICES="0,1"

LINGBOT_REPO="\${SOURCE_ROOT}/lingbot-va"
DREAMZERO_REPO="\${SOURCE_ROOT}/dreamzero"
LIBERO_REPO="\${SOURCE_ROOT}/LIBERO"

LINGBOT_CKPT_DIR="\${PROJECT_ROOT}/checkpoints/lingbot-va-posttrain-libero-long"
DREAMZERO_CKPT_DIR="\${PROJECT_ROOT}/checkpoints/DreamZero-DROID"
DREAMZERO_AGIBOT_CKPT_DIR="\${PROJECT_ROOT}/checkpoints/DreamZero-AgiBot"
LIBERO_DATA_DIR="\${PROJECT_ROOT}/data/libero"
LOG_DIR="\${PROJECT_ROOT}/robot_wam_h800_probe_and_run/logs"

LINGBOT_ENV_NAME="lingbot_va"
DREAMZERO_ENV_NAME="dreamzero"
LIBERO_ENV_NAME="libero"

LINGBOT_MODEL_ID="robbyant/lingbot-va-posttrain-libero-long"
LINGBOT_MODELSCOPE_ID="Robbyant/lingbot-va-posttrain-libero-long"
DREAMZERO_DROID_MODEL_ID="GEAR-Dreams/DreamZero-DROID"
DREAMZERO_AGIBOT_MODEL_ID="GEAR-Dreams/DreamZero-AgiBot"

LINGBOT_PORT="29056"
LINGBOT_MASTER_PORT="29061"
DREAMZERO_PORT="5000"
DREAMZERO_API_HOST="127.0.0.1"
DREAMZERO_API_PORT="5000"
EOF

echo "Wrote ${CONFIG_FILE}"
echo "PROJECT_ROOT=${PROJECT_ROOT}"
echo
echo "Expected source repos:"
echo "  ${PROJECT_ROOT}/sources/lingbot-va"
echo "  ${PROJECT_ROOT}/sources/dreamzero"
echo "  ${PROJECT_ROOT}/sources/LIBERO"
